### PR TITLE
Wrong btn class

### PR DESCRIPTION
**Pull request by freshface**
The btn was green, but should have a default class

## Type

- Enhancement

### CODE REVIEW

**Comment by carakas** [comment]
can you give a bit more context or a screenshot?

**Comment by freshface** [comment]
This btn is green. https://jmp.sh/Clmz7I8
Kinda weird for a green button in that place, after the changes it looks like this https://jmp.sh/dBWTVjF
Makes more sense?

**Comment by jeroendesloovere** [comment]
The current colors make more sence to me.
Red = delete
Green = add

schermafbeelding 2018-07-02 om 16 15 30

**Comment by jeroendesloovere** [comment]
Perhaps we should change the "Publish" color to green too.

schermafbeelding 2018-07-02 om 16 17 27

**Comment by freshface** [comment]
I see green as a feedback/success color, not as a primary button color.

**Comment by jeroendesloovere** [comment]
@freshface thanks for your PR!
I believe this points out a greater problem in the UI colors.

- We practically always use "red" for "deletions". Which is good.
- But we do use "green", "grey" and "blue" for additions/savings... This could indeed be better and be made more uniform. 

@Katrienvh Do you know if there was any particular reason this was done like this?

**Comment by freshface** [comment]
A red button is fine by me because it removes something which has more impact then adding something.

**Comment by carakas** [comment]
not going to change this one

**Pull request closed without merging**
