### PR TITLE
Add header image to readme

### PR DESCRIPTION
**Pull request by jessedobbelaere**
## Type
- Enhancement

## Resolves the following issues
Make header more appealing as an open-source project. Better use of the great branding we have.

## Pull request description
* Adds a header image to the docs folder which we can reference (once merged, right now link is broken ofcourse)
* Added a docs badge linking to the documentation site

End result looks like this:

screen shot 2017-06-25 at 00 21 33

### CODE REVIEW

**Comment by GhaziTriki** [comment]
I get a 404 error when I try to load the header image.

**Comment by jessedobbelaere** [comment]
Yeah that's normal :) . It's because the image refers to the master branch, and this is the fork v5 branch. When the Fork V5 branch gets merged into master, it'll work

--> https://raw.githubusercontent.com/forkcms/forkcms/master/docs/img/header.jpg)

**Comment by carakas** [comment]
@jessedobbelaere why not make the path relative? Then it will work

**Comment by jessedobbelaere** [comment]
Didn't know that that was possible when I was searching for embedded images from inside the repo, anyway PR created! See https://github.com/forkcms/forkcms/pull/2128

**Pull request merged**
