### PR TITLE
Install theme uploads with different zip folder structures

### PR DESCRIPTION
**Pull request by jessedobbelaere**
## Type
- Enhancement
## Resolves the following issues

Given: a user downloads a theme from Github using a ZIP file. He uploads it to Fork using upload_module action
Then: he gets an error "The theme's folder name doesn't match the theme name in info.xml."

The validation is way too strict. You need a zip with a foldername thats exactly the same name as the theme inside info.xml. Uppercase or lowercase difference? No, theme will not upload. 
Downloaded a theme from github? No, theme won't upload due to the zip structure
## Pull request description

Did an attempt to allow multiple zip structures to be uploaded correctly. 

The code will find the folder that contains the info.xml file. Then it will ONLY extract these files in that folder. It won't extract files outside of the theme folder. 
If there is no parent folder with the theme name extracted in the zip, it will create/rename it to the appropriate theme folder in `src/Frontend/Themes`.

You can have these zips and they will all upload correctly:
#### Examples
1. A zip that only contains the files and folders of the theme. No parent folder with exactly the theme's name inside the zip. Just loose files. 
   screen shot 2016-10-25 at 02 35 00

Download: 
[chameleon-folder-zipped.zip](https://github.com/forkcms/forkcms/files/549345/chameleon-folder-zipped.zip)
1. A zip that contains a folder with the theme's name with files. This is the way we were used to. 
   screen shot 2016-10-25 at 02 34 34

Download: 
[chamelon-individual-files.zip](https://github.com/forkcms/forkcms/files/549346/chamelon-individual-files.zip)
1. A zip that contains a different foldername with files than the themename in info.xml. This is the zip that you download directly from github! That should succeed as well. 
   screen shot 2016-10-25 at 02 34 50

Download: 
[fork-cms-theme-chameleon-master.zip](https://github.com/forkcms/forkcms/files/549347/fork-cms-theme-chameleon-master.zip)

### CODE REVIEW

**Comment by jessedobbelaere** [comment]
btw any clue how this can be unit tested easily?

**Comment by carakas** [comment]
can you base64 a zip? :p

**Comment by jessedobbelaere** [comment]
I guess so :D We would just need to programatically create a zip with a parent folder and info.xml using the `addFromString` and `addEmptyDir`.

<details>
```
$zipStr = 'UEsDBBQACAAIABprdEEAAAAAAAAAAAAAAAAWAAAAb2JqZWN0cy9Db250YWN0Lm9iamVjdI2SX0vDMBTF3/cpSt9NOhERyTJCl+Gga6VNBZ9GlmWuI21mk0799ka7P50TXR4C9+R3L5ecg4bvpfK2sjaFrgZ+HwS+JyuhF0X1MvBzNr6684e4h8LGWF0m87UU1nMtlRn4K2s39xAazTfALHUtJBC6hNdBcAuDG1hKyxfcch/3PHeQKox9KuSbaetvbdkoFfNSYqEry4WdpXxdzBE86EdUaNWUlcHjPIpmMZlSBPfSOUTCMMljBv7jwiRmJGSATVh0Efj4kMS0fwlJp2QS/Q2mFOQZTTNAognJfmOXhbKyzoTeSEydSx925Yxx/9PRf9Kd/p0q1eKwVphSwuhoNnL315yvt1Pezay5dXHAShqT1PS14QrBo3yKb7lqJGbJiDwj2BbHjeDZSkjxuVR7v72d363Y5gR2goJgN3i49wlQSwcI3kTEMT8BAACvAgAAUEsDBBQACAAIABprdEEAAAAAAAAAAAAAAAALAAAAcGFja2FnZS54bWxNj00LwjAMhu/7FaN3lzpkiHTdQfDkQUS9StbFWbXtWIsf/96xDzSX5CF53ySieJtH/KTWa2dzNk84i8kqV2lb5+x42MyWrJCR2KG6Y01xN219zq4hNCsA77BJ/MW1ihLlDKScZ8AXYChghQGZjOIuRPg05Ie6Z0Om7FbKtbMBVei0fT7v8aZLAVP7J7BoSG61DydNLwE9Dtbw5y3GP2SaJVzARJGA8XwZfQFQSwcIaf0pNKsAAADwAAAAUEsBAhQAFAAIAAgAGmt0Qd5ExDE/AQAArwIAABYAAAAAAAAAAAAAAAAAAAAAAG9iamVjdHMvQ29udGFjdC5vYmplY3RQSwECFAAUAAgACAAaa3RBaf0pNKsAAADwAAAACwAAAAAAAAAAAAAAAACDAQAAcGFja2FnZS54bWxQSwUGAAAAAAIAAgB9AAAAZwIAAAAA';

// Prepare Tmp File for Zip archive
$file = tempnam("tmp", "zip");
$zip = new ZipArchive();
$zip->open($file, ZipArchive::OVERWRITE);

// Add contents
$zip->addFromString('your_file_name', base64_decode($zipStr));

// Close and send to users
$zip->close();
```
</details>

Or just add 3 real zip's with some textfiles in the tests folder

**Comment by carakas** [comment]
I would create them in the code

**Comment by carakas** [comment]
and remove them after the tests

**Comment by StijnVrolijk** [comment]
Note to self: merge on Oct 31st if tests weren't added yet

**Comment by jessedobbelaere** [comment]
Created some tests, runs perfectly on php 5.6 and 7, but somehow travis fails. Could use some help to fix that. It's creating some conflict with other tests.

**Pull request merged**
