### PR TITLE
Fixes #1198, generating meta url with special characters.

### LINKED ISSUE #1198: BUG: Special characters in Page URL.
**Problem**
When trying to add a page with special characters. We don't want the URL to use these special characters. But the result is not what we expect.

**Steps to reproduce**

* Pages > Add page
* Type in "électricité"
* You see the correct URL, without special characters (by AJAX call generateUrl)

schermafbeelding 2015-05-19 om 08 56 45

* But when you save, the URL gets transformed to something wrong

schermafbeelding 2015-05-19 om 08 56 53

### PR DESCRIPTION
**Pull request by jeroendesloovere**
Fixes #1198

### CODE REVIEW

**Comment by WouterSioen** [comment]
:+1:

**Comment by WouterSioen** [comment]
Tests for this functionality would be awesome and something to provide in the future, since this is something we already had issues with multiple times.

**Comment by tijsverkoyen** [comment]
I think squashing the commits would be nice here.

**Comment by jeroendesloovere** [comment]
@WouterSioen Can you add "squashing" information in the [Contributing.md](https://github.com/forkcms/forkcms/blob/master/CONTRIBUTING.md) file so contributors can do this.

**Comment by WouterSioen** [comment]
I'll add this

**Comment by WouterSioen** [comment]
https://github.com/forkcms/forkcms/commit/b08c18b416cd4da987e93b50b8fcc598c16ad38c

**Comment by jeroendesloovere** [comment]
@WouterSioen Thanks

**Comment by WouterSioen** [comment]
I'll merge this

**Comment by WouterSioen** [comment]
merged in 4f8d4f957a8f31d421163fbaebe82fde230198dc

**Pull request closed without merging**
