### PR TITLE
Updated CKFinder to version 2.6.2

### PR DESCRIPTION
**Pull request by GhaziTriki**

### CODE REVIEW

**Comment by tijsverkoyen** [comment]
:+1:

**Comment by carakas** [comment]
@GhaziTriki it didn't work, when I tried to upload an image the ajax call returned Invalid request.

**Comment by GhaziTriki** [comment]
I have merged master to it then tested. I had no issues putting an image in a new content block and displaying it in a page.

**Comment by GhaziTriki** [comment]
Here https://cksource.com/ckfinder/whatsnew it says that a issue with HTML5 upload with IE has been fixed. I will update this PR.

**Pull request merged**
