### PR TITLE
Fixes Analytics ConnectorTest

### PR DESCRIPTION
**Pull request by jeroendesloovere**
Which throws error because ```the namespace PHPUnit_Framework_TestCase``` not exists.

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
When deploying using Capistrano the deployment fails on this.
This is a working solution.

**Comment by WouterSioen** [comment]
using a use statement is just as good as adding a backslash. I don't get how this could fix any issues. It's exactly the same code, just with another syntax.

**Comment by jeroendesloovere** [comment]
When I do this fix, I can ```cap production deploy``` again.
Otherwise it throws fatal error and will rollback.
```php
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /apps/production/releases/xxx/src/Backend/Modules/Analytics/Tests/GoogleClient/ConnectorTest.php on line 16
```

**Comment by jeroendesloovere** [comment]
Don't know why, because in the Common folder there are also tests where the ```use``` statement has been used.

**Comment by jeroendesloovere** [comment]
Conclusion:
in modules we should use ```\PHPUnit_Framework_TestCase``` to make everything work in production.

**Comment by WouterSioen** [comment]
`extends \PHPUnit_Framework_TestCase` is *exactly* the same as `use PHPUnit_Framework_TestCase` and `extends PHPUnit_Framework_TestCase`

I don't see how this could make any difference.

**Comment by WouterSioen** [comment]
@jeroendesloovere can you test this in this code base and PR it in there if your problem still exists? https://github.com/forkcms/forkcms/pull/1447

**Pull request closed without merging**
