### PR TITLE
Add Symfony style functional tests (WebTestCase) to the InstallerBundle

### PR DESCRIPTION
**Pull request by WouterSioen**
There already is an open pull request with automatic tests (https://github.com/forkcms/forkcms/pull/983). This PR tries to integrate almost the same tests, but using the Symfony WebTestCase. This makes the tests a lot easier to understand and write for Symfony developers.

### CODE REVIEW

**Comment by WouterSioen** [comment]
Note that some of these commits should be squashed when merging, since I had some trouble getting the tests to work in travis.

**Comment by WouterSioen** [comment]
@ghazispeakserve I'd like your feedback on this one since you already implemented functional tests in the installerbundle.

I think this version is more "the Symfony way" and easier for more developers to add. But it could be that you have some feedback from your experience from adding codeception tests.

**Comment by ghazispeakserve** [comment]
After taking a look at it is an improved "Symfonysed" version of my tests integration. If unit tests with phpunit can cover we need initially it is good. We can still move to codeception if we want to implement acceptance like checking the backend layout behaviour. This is my advice. Keep the good work I am still impressed by the community politeness.

**Comment by WouterSioen** [comment]
@forkcms/core-contributors any feedback on this?

**Comment by matthiasmullie** [comment]
:shipit:

**Comment by tijsverkoyen** [comment]
:+1:

**Pull request merged**
