### PR TITLE
Dont index content for search

### PR DESCRIPTION
**Pull request by freshface**
Dont index content for search if authentication for the page is true.

## Type

- Enhancement

## Resolves the following issues

Dont index the page content of authentication for the page is true, else it will show up inde search results.

### CODE REVIEW

**Comment by carakas** [comment]
@freshface code style checks failed, can you look at this: https://styleci.io/analyses/qv07Wr

**Comment by carakas** [comment]
Apart from that, I think it should be an option on the authentication page to remove it from the search and not something you can't do anything about

**Comment by freshface** [comment]
Ok, how do we fix it?
On a "per page" base or as a general setting for the pages module "Don't search  index pages which are authenticated"

**Comment by carakas** [comment]
I would do it per page in the authentication tab

**Comment by carakas** [comment]
@freshface any update on this?

**Comment by freshface** [comment]
I am checking the feedback atm.

**Comment by freshface** [comment]
I changed it.

**Pull request merged**
