### PR TITLE
Pass container to models in WebTestCase

### PR DESCRIPTION
**Pull request by jessedobbelaere**
## Type

- Non critical bugfix

## Resolves the following issues

When running a WebTestCase test like `./bin/phpunit -c phpunit.xml.dist src/ForkCMS/Bundle/InstallerBundle/Tests/Controller/InstallerControllerTest.php` I get the following error:

<details>

```
1) ForkCMS\Bundle\InstallerBundle\Tests\Controller\InstallerControllerTest::testnoStepActionAction
Error: Call to a member function getParameter() on null

/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/src/Frontend/Core/Engine/TwigTemplate.php:38
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:314
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:185
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/src/ForkCMS/Bundle/InstallerBundle/Controller/InstallerController.php:39
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:64
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php:69
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/app/Kernel.php:55
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Client.php:79
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:131
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:315
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:499
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/src/ForkCMS/Bundle/InstallerBundle/Tests/Controller/InstallerControllerTest.php:14

2) ForkCMS\Bundle\InstallerBundle\Tests\Controller\InstallerControllerTest::testInstallationProcess
Error: Call to a member function getParameter() on null

/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/src/Frontend/Core/Engine/TwigTemplate.php:38
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:314
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:185
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/src/ForkCMS/Bundle/InstallerBundle/Controller/InstallerController.php:69
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:64
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php:69
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/app/Kernel.php:55
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Client.php:79
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Client.php:131
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/vendor/symfony/symfony/src/Symfony/Component/BrowserKit/Client.php:315
/Users/jessedobbelaere/Dropbox/www/fork-cms/fork-cms-github/src/ForkCMS/Bundle/InstallerBundle/Tests/Controller/InstallerControllerTest.php:38

FAILURES!
Tests: 2, Assertions: 0, Errors: 2.
```

</details>

I started looking into src/Frontend/Core/Engine/TwigTemplate and here is where the error occurs:

```
$this->debugMode = Model::getContainer()->getParameter('kernel.debug');
```

Looks like Model::getContainer is null. The fix in my PR solves the issue and I can (finally) run all phpunit tests in forkcms!

## Pull request description

I pass the container to the models right after loading the kernel in the WebTestCase phpunit tests. Now they're not null. 
(how does travis not give errors on that? What's different in my setup?)

### CODE REVIEW

**Comment by jessedobbelaere** [comment]
1 failing test. For some reason, this block gets executed:

https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Engine/TwigTemplate.php#L40-L43

```
$this->forkSettings = Model::get('fork.settings');
        // fork has been installed
        if ($this->forkSettings) {
            $this->themePath = FRONTEND_PATH . '/Themes/' . $this->forkSettings->get('Core', 'theme', 'default');
             ...
```

fork ModuleSettings contains a $database and a $cache by default. So it won't be null... How to fix?

**Comment by carakas** [comment]
@jessedobbelaere do you need help to fix this bug?

**Comment by jessedobbelaere** [comment]
Yeah, wouldn't hurt to have an extra pair of eyes :-) we can discuss on slack if needed

**Comment by carakas** [comment]
@jessedobbelaere should be fixed now with #2003

**Pull request closed without merging**
