### PR TITLE
Hide navigation and header in modal mode

### PR DESCRIPTION
**Pull request by ohvitorino**
## Type

- Feature

## Pull request description

The idea behind this pull request is to be able to open Fork backend pages from within Fork as a popup/modal, and when using this feature, the navigation and header should be hidden. This is a useful feature if we want to open a popup with the media library in it, for example.

Example:

screen shot 2017-08-31 at 15 38 56

### CODE REVIEW

**Comment by carakas** [comment]
@ohvitorino can you  post a screenshot?

**Comment by ohvitorino** [comment]
I realised I was using the wrong css classes. My initial solution will only work for the dashboard. I need to improve this.

**Comment by ohvitorino** [comment]
@carakas I'll also post a screenshot.

**Comment by jeroendesloovere** [comment]
I see why you want to integrate this functionality.
Could give us some nice new features.

**Comment by ohvitorino** [comment]
@carakas I just notice, a problem with this solution. After the initial Fork installation, Fork gives the user the possibility to go to the backend using the same technique as the one used to open modal popups. This means the sidebar and header will also be hidden in this case, and therefore this shouldn't be merged.

**Comment by ohvitorino** [comment]
@carakas Indeed. Close this one. If it's necessary to have such a functionality again, we'll have to think of something else.

**Pull request closed without merging**
