### PR TITLE
Add placeholder to textbox and textarea elements

### LINKED ISSUE #1083: Formbuilder placeholders & classnames
I often use formbuilder, but one of the features that it lacks is placeholders. Would it be a good idea if I add an input field "placeholder" to each field where you can enter a placeholder text? 

I also find it hard to style a form. The form widget gets an id like `#form3` but that's not really useful in CSS because it could change. Maybe add a general form css class(es) input field to the form? The [Extra tab](http://cl.ly/image/2L2X2U342S1G) is probably the best place for this.

I would also find it useful to have a CSS class input field in the properties panel of each field. (I would then add that css class name on the wrapper div of the field including the label and input field, so you can use the wrapper classname to target the label or input field). 

If I add some of these options, then it would be way easier to create a more visually appealing layout for your form using CSS. I don't think that this is much work to implement? Other suggestions to improve formbuilder?

### PR DESCRIPTION
**Pull request by jessedobbelaere**
Adds a "placeholder" input field to the Formbuilder when you create a textbox or textarea element. This gives you the possibility to add placeholder text to the input field if you want.

Example: 
image

Or should I put a line between the "default value" and the "placeholder" input field?

Frontend:

image

This fixes #1083

### CODE REVIEW

**Comment by WouterSioen** [comment]
I'd add the placeholder in an extra tab "advanced options". Developers and frontenders know what a placeholder is, but most users don't. I wouldn't show inputs to them that might confuse them.

**Comment by WouterSioen** [comment]
Implementation itself looks clean btw :+1: (even though the formbuilder really needs some clean up)

**Comment by Thijzer** [comment]
@jessedobbelaere Did you render the placeholder in the backend form? For good measure.

**Comment by WouterSioen** [comment]
Looks like this is done: https://github.com/forkcms/forkcms/pull/1117/files#diff-0fe346a14b3ad044cbb13455f22c4ef8R121

**Comment by WouterSioen** [comment]
Zo'n helptekstje kan mss een alternatief zijn voor een extra tab.

**Comment by jessedobbelaere** [comment]
I added an Advanced tab :+1: 

image

@Thijzer Yes, the placeholder is also rendered in the backend preview form.

image

**Comment by Thijzer** [comment]
Looks good and clean indeed.

**Comment by WouterSioen** [comment]
:+1: can be merged IMO

**Comment by jessedobbelaere** [comment]
Great :+1: Meanwhile, I already used this on a live website to add placeholders to the form and it works great

**Comment by WouterSioen** [comment]
@jessedobbelaere it seems like something was lost when merging the bootsrap layout in the 3.10 branch. Do you have some time to look into fixing this?

**Comment by jessedobbelaere** [comment]
Yep I'll take a look into the 3.10 branch :+1:

**Comment by jessedobbelaere** [comment]
@WouterSioen Hmm i'm trying to add placeholders but there seem to be some other things missing from the formbuilder module in the 3.10 branch. Things like validation dropdown (e-mail, numeric, ) etc? 

image

**Comment by WouterSioen** [comment]
It would be lovely if you could add these in the layout too then. It was a real mess to merge the bootstrap layout with all the new features, so it could be possible that some of these got lost. If you don't have time, I'll check when I can do this.

**Comment by jessedobbelaere** [comment]
Working on my master thesis, but fixing this normally won't take up a lot of time. I'll do my best!

**Comment by WouterSioen** [comment]
great!

**Comment by WouterSioen** [comment]
@jessedobbelaere didn't find any time for this? :) It's not that urgent, but it would be nice if we could release the 3.10 release somewhere soonish.

**Comment by jessedobbelaere** [comment]
Sorry, finishing my master thesis during the next 10 days and then I'll have some spare time to take a look :smiley:

**Comment by WouterSioen** [comment]
Good luck with your thesis!

**Pull request merged**
