### PR TITLE
update local.xml: delete duplicate item end tags

### PR DESCRIPTION
**Pull request by bramds**
## Type

- Non critical bugfix

## Resolves the following issues
delete duplicate item end tags that stopped the local import

### CODE REVIEW

**Comment by carakas** [comment]
fastest merge ever

**Comment by StijnVrolijk** [comment]
Fastest merge ever

**Comment by jeroendesloovere** [comment]
fastest merge ever

**Comment by carakas** [comment]
@jeroendesloovere late at the party

**Comment by jeroendesloovere** [comment]
Closes https://github.com/forkcms/forkcms/issues/2586

**Comment by jeroendesloovere** [comment]
@carakas I know ✌️ 
Just checking in here to finish everything
and closing an issue that you guys forgot in all the enthusiasm.

**Pull request merged**
