### PR TITLE
Street view integrated in back-en frontend

### PR DESCRIPTION
**Pull request by jeroendesloovere**
Closes #1410

### CODE REVIEW

**Comment by WouterSioen** [comment]
We've tested this and the location changed when editing a map in street view mode.

**Comment by carakas** [comment]
you should pull master before working on it because there was a bug that prevented the map settings from being saved. (and then you can fix the merge conflicts)

**Comment by carakas** [comment]
closes #542

**Comment by carakas** [comment]
@jeroendesloovere can you fix the conflicts?

**Comment by carakas** [comment]
poke @jeroendesloovere

**Pull request merged**
