### PR TITLE
3.10

### PR DESCRIPTION
**Pull request by vytenizs**
Updates and merge with master. Updated Common/Core/Form.

### CODE REVIEW

**Comment by WouterSioen** [comment]
The tests aren't green anymore. Seems like the edit user test page title doesn't contain "Users: edit user "Users User"" anymore. Can you look into this?

**Comment by vytenizs** [comment]
Ok ill look ASAP.

**Comment by vytenizs** [comment]
Cant run test locally, throws PHP Fatal error:  Class 'Doctrine\Tests\Common\Cache\CacheTest' not found in.
I load fork autoload.php. But this error still happens.

**Comment by WouterSioen** [comment]
I see you've managed to fix the tests. Were you able to run it? I guess you didn't specify the location of the tests configuration file?

**Comment by vytenizs** [comment]
Yep i fixed it, but was unable to run tests on PhpStorm. I tried to use local phpunit and not travis. I will try to use travis.

**Comment by WouterSioen** [comment]
Your local phpunit can work, but the configuration is in the app directory.

the command phpunit should thus be suffixed with `-c app`

**Comment by vytenizs** [comment]
Ok main reason is that i did not had *_test database. Now tests run but all responses are 500.

**Comment by WouterSioen** [comment]
you can take a look in the app/logs/logs.log to see why you get 500 responses.

**Comment by vytenizs** [comment]
Ok ill try to figure this out. Thanks for help :)

**Comment by WouterSioen** [comment]
I've made a PR that should make debugging these things easier: #1234

**Comment by vytenizs** [comment]
OK cool :)

**Pull request merged**
