### PR TITLE
set module js files to minify and remove timestamp

### PR DESCRIPTION
**Pull request by vytsci**

### CODE REVIEW

**Comment by WouterSioen** [comment]
why removing the timestamp?

**Comment by carakas** [comment]
why would you remove the timestamp ? this can help for caching

**Comment by carakas** [comment]
I would also not minify when the site is in debug mode

**Comment by vytsci** [comment]
Sorry did not see that timestamp is last modified. Thought its preventing js for caching with current time timestamp.

**Comment by vytsci** [comment]
Well this should be done in other place. Withing minifying algorithm.

**Comment by vytsci** [comment]
and there it is
// no minifying when debugging
        if ($this->getContainer()->getParameter('kernel.debug')) {
            $minify = false;
        }

**Comment by carakas** [comment]
ok nice, I did not know that 👍 awesome :D

**Comment by carakas** [comment]
did you test in all the core modules that the minifying doesn't result in javascript errors ? if that is the case you get my 👍

**Comment by vytsci** [comment]
Nope have not tested anything. Just checked that minifying works. Solving minifying errors is not the case at this point. If minifier is not working properly it should be a different PR with minifier fix.

**Pull request merged**
