### PR TITLE
Russian language in locale.xml module MediaLibrary

### PR DESCRIPTION
**Pull request by linbis**
## Type

- Enhancement

## Pull request description

Added translations in file Backend\Modules\MediaLibrary\Installer\Data\locale.xml 
into Russian language in nodes Core and MediaLibrary

### CODE REVIEW

**Comment by carakas** [comment]
@linbis is it possible that you didn't get the explanation on the previous PR? Cause you are making the same mistake again

Also, your js fix should be in a separate PR

Can you please fix this or I'll have to close your PR again without merging

**Comment by linbis** [comment]
Ok. I will make changes

**Comment by carakas** [comment]
Thank you, feel free to ask if you have any questions

**Comment by carakas** [comment]
@linbis did you find some time to fix this?

**Pull request merged**
