### PR TITLE
Added Google Maps API key.

### PR DESCRIPTION
**Pull request by bartdc**
https://developers.google.com/maps/documentation/geocoding/get-api-key#key

A server key is needed when using JSON in Model.php.

### CODE REVIEW

**Comment by WouterSioen** [comment]
Looks good to me

**Comment by jeroendesloovere** [comment]
@bartdc, doesn't the frontend needs the apikey as well?

**Comment by bartdc** [comment]
@jeroendesloovere No. The API key is needed when using geolocation to retrieve coordinates. You don't need a key to put a marker on the map.

**Comment by jeroendesloovere** [comment]
Hi @bartdc, it is not required, but recommended (to view stats, ...).
https://developers.google.com/maps/signup

**Comment by bartdc** [comment]
@jeroendesloovere Good point. And now that the key is available, we can use it easily. To be continued.

**Comment by WouterSioen** [comment]
@bartdc will you add the key in the frontend in this pull request or in a new one?

**Comment by bartdc** [comment]
Will be in this PR, this weekend or next week.

**Comment by WouterSioen** [comment]
ok, no problem, many thanks for the contributions!

**Pull request merged**
