### PR TITLE
Use templating services

### PR DESCRIPTION
**Pull request by WouterSioen**
Follow up on #1351 (since @Thijzer doesn't have a lot of time anymore)

Changes:

- [x] Use a templating service instead of `new TwigTemplate()`
- [x] Make all tests pass
- [x] Clean up some code.
- [x] Avoid nasty things like `ob_start` and `ob_get_clean`

All feedback is welcome on  this!

### CODE REVIEW

**Comment by WouterSioen** [comment]
@tijsverkoyen @Thijzer do you have some time to look into this? IMO, it can be merged in the 3.10 branch. (Some parts could still be a little cleaner, but everything works and we can further refactor later too).

I'd like to see this merged soon, because it changes a lot of stuff, and further PR's to the 3.10 branch should depend on this (to avoid merge conflicts)

**Comment by Thijzer** [comment]
Hi @WouterSioen, thanks for picking it up where I left off.
Yes if been a bit busy with my new job.. :/

I can take a look tomorrow evening, if that's ok..

**Comment by WouterSioen** [comment]
@Thijzer that would be very nice :)

**Comment by Thijzer** [comment]
twig file render errors

here are the routes
/private/en/pages/edit?token=bv0hynt11w&id=412
/private/en/locale/index
/private/en/users/index datagrid raw
/private/en/groups/index datagrid raw
/private/en/extensions/modules datagrid raw

I only checked the backend minimal install modules...

php errors 
/private/en/search/settings illegal offset type

Frontend defaults to spoon tpl because of the paramater, remove the method and accurances of method getTemplateType. this was a BC trick so make sure the template parameter in your yml file is removed.

voila, 
Hope this helps.

**Comment by WouterSioen** [comment]
Thanks for checking it, I'll look into it!

**Comment by WouterSioen** [comment]
@vytenizs if you want to help, it would be awesome if you could test this branch (and do some PR's if needed). I want to get this one merged asap, to be able to implement the new design on twig instead of SpoonTemplate.

**Comment by vytenizs** [comment]
Ok ill merge this on my new project and test it ASAP.

**Comment by WouterSioen** [comment]
great! You might still get a lot of errors though ;)

**Comment by WouterSioen** [comment]
included in https://github.com/forkcms/forkcms/pull/1447

**Pull request closed without merging**
