### PR TITLE
Improve Github issue & PR templates

### PR DESCRIPTION
**Pull request by jessedobbelaere**
## Improvement

| Q           | A      |
| ----------- | ------ |
| Improvement | yes    |
| RFC         | yes |
| BC Break    | no |

### Summary

Heavily inspired by Doctrine ORM's github setup:

image

I would like to introduce this in Fork CMS. 
Something like:

- :boom: Critical Bug
- :beetle: Bug Report
- :sparkles: Feature Request
- :question: Support Question
- Report a security vulnerability

I left out "Enhancement" that we used to have, as reporting an Enhancement is almost identical to reporting a Feature Request

Same goes for PR templates...

### CODE REVIEW

**Comment by carakas** [comment]
@jessedobbelaere can you also make pull request templates for bugfixes? Or is there a reason you didn't make those?

**Comment by jessedobbelaere** [comment]
@carakas it's part of the "Improvement" PR template

> You have a bugfix or improvement to make Fork CMS better? 🎁

Basically I looked at Doctrine, https://github.com/doctrine/orm/tree/master/.github/PULL_REQUEST_TEMPLATE

But maybe we should make it more obvious, change the name to `Improvement/bugfix` ?

**Comment by carakas** [comment]
I would make it more obvious indeed 👍

**Comment by jessedobbelaere** [comment]
Cool, I modified the title to "Bugfixes and Improvements

**Pull request merged**
