### PR TITLE
[WIP] Fixed Analytics in Backend: return type was wrong

### PR DESCRIPTION
**Pull request by jeroendesloovere**
## Type

- Critical bugfix

## Resolves the following issues

The return type is not `array`, but `Google_Service_Analytics_GaData`.

## Pull request description

GoogleClient Connector return type for getAnalyticsData was falsely set to `array`,
this must be `Google_Service_Analytics_GaData` instead.

### CODE REVIEW

**Comment by carakas** [comment]
Not sure it always is that return type because I remember changing it because I was getting errors to array
https://github.com/jeroendesloovere/forkcms/commit/5659bda83e20201f54c9b1bd4cfb8ffbb8ed6d7c

**Comment by jeroendesloovere** [comment]
Hi @carakas, Google returns `Google_Service_Analytics_GaData`, which extends ArrayAccess, so $data['rows'] is possible for example.

[WIP]
Because, I'm experiencing data-pie-chart issues (there are not showing up). So I'm looking further into this.

**Comment by jeroendesloovere** [comment]
`array` return type is not a possiblity because that breaks the Backend.

**Comment by carakas** [comment]
can you check in all the places that lead to this method, because I won't have changed it for fun and giggles

**Comment by carakas** [comment]
@jeroendesloovere there have been some big js changes already in this branch, can you maybe first make sure that it is up to date

**Comment by carakas** [comment]
@jeroendesloovere check travis, the array issue :)

**Comment by jeroendesloovere** [comment]
Keeping array seems more future-proof.
So closing this for: #2317

**Pull request closed without merging**
