### PR TITLE
Make it possible to reply to a blog comment

### LINKED ISSUE #2004: There is no way to reply as site owner to a blog comment
## Type

- Feature

## Problem description

People can leave comments on your blog but there is no way to reply to them as owner.

## Expected behavior / Proposed solutions

It would be nice if it was added and send a notification to the person that posted the comment

### PR DESCRIPTION
**Pull request by carakas**
## Type

- Feature

## Resolves the following issues

fixes #2004 

## Pull request description
This PR adds the option for authors to reply to a blog post comment, the person that left the comment will also be notified
Frontend:
screen shot 2017-10-18 at 14 33 10

Backend:
screen shot 2017-10-18 at 14 33 27

### CODE REVIEW

**Review by StijnVrolijk — APPROVED** [review]

**Comment by tijsverkoyen** [comment]
If I understand it correctly, you can only reply from the backend? 
In my opinion this doesn't add real value, it would be more useful to implement a threaded-comment-system. So everyone can reply on specific comments instead of only the users with access to the backend.

**Comment by carakas** [comment]
@tijsverkoyen  the added value here is that it allows site owners to reply to a comment and actually notify the person that left the comment automatically.
A full threaded comment system is not something we can implement in an easy way because that would most likely result in database changes, we can always create an issue for that to address it in fork 6 but I'm not sure how relevant this is.

This is something I've actually heard people say they missed it or actually assumed it was possible.

**Comment by tijsverkoyen** [comment]
In my personal opinion: The blog-module is around since the start of Fork CMS, in that time nobody has asked met to be able to reply on a specific comment as an author. A threaded commenting-system is something that was requested.

So in my opinion, this PR does not add a lot of value, and I would be more enthusiastic for a threaded system, which resolved the problem you are trying to solve here also.

**Comment by carakas** [comment]
@forkcms/core-contributors @forkcms/backenders @forkcms/frontenders any other opinions?

**Comment by mathiashelin** [comment]
I'd go for threaded comments or nothing add all.

**Pull request closed without merging**
