### PR TITLE
require symfony/var-dumper

### PR DESCRIPTION
**Pull request by carakas**

### CODE REVIEW

**Comment by WouterSioen** [comment]
@carakas can you squash your commits?

I'm all in favor of adding this component!

**Comment by carakas** [comment]
@WouterSioen done

**Comment by WouterSioen** [comment]
Good :+1:

**Comment by StijnVrolijk** [comment]
:+1:

**Comment by WouterSioen** [comment]
fixed in 55a41c6 (since merging this will cause merge conflicts)

**Pull request closed without merging**
