### PR TITLE
Increase minimum php version to 5.6

### PR DESCRIPTION
**Pull request by carakas**
PHP 5.5 reaches EOL on 10 Jul 2016, after that we no longer support it for security reasons

### CODE REVIEW

**Comment by jessedobbelaere** [comment]
Nice 👌

(haters gonna hate)

**Comment by WouterSioen** [comment]
this was on my planning for the 10th, you beat me to it :D

**Comment by WouterSioen** [comment]
this is BC breaking though, so this should be done in a major release...

**Comment by carakas** [comment]
well, lucky 5.5 users :p they get extra support just because we recently released 4.0.0 :p

**Comment by WouterSioen** [comment]
if we upgrade to fork 5.0.0 after 1 january, we should even bump to php 7

**Pull request closed without merging**
