### PR TITLE
3.10

### PR DESCRIPTION
**Pull request by mathiashelin**
Major changes:
* Use Sass in combination with Bootstrap-sass so we can configure all variables
* Remove Bootstrap-theme because it makes everything glossy and ugly
* Remove Bootstrap from bower dependencies
* Use bootstrap.js instead of jquery-ui.js if possible
* Style form errors
* Use Font Awesome instead of Glyphicons
* Use Bootstrap tooltip instead of default abbr-tag
* Remove module-specific css if possible
* Add Fork logo to sticky footer
* Fix minor layout bugs in entire backend

### CODE REVIEW

**Comment by WouterSioen** [comment]
Can some screenshots be added?

**Comment by mathiashelin** [comment]
screen shot 2016-01-15 at 09 37 42
screen shot 2016-01-15 at 09 38 03
screen shot 2016-01-15 at 09 38 35
screen shot 2016-01-15 at 09 39 12

**Comment by WouterSioen** [comment]
Looks great :+1:

**Comment by simohell** [comment]
Guys, really? This doesn't look good at all. Thumbs up for using bootstrap and updating everything, but visually this doesn't look good!

**Comment by WouterSioen** [comment]
@simohell do you have any suggestions to improve the layout?

**Comment by simohell** [comment]
@WouterSioen The layout of fork might be a bit dated but i think it still holds up today. Just changing it to bootstrap doesn't make it better, the code may be better but that's it. 

I remember when working at Netlash when Johan was designing Fork NG very carefully after Bram had made an extensive prototype... I just don't think we can "bootstrap" Fork like this. If the UI get's an overhaul it's not just design, there should be someone with IA/UX background involved.

Ideas, yes i have some, but haven't got the time to make a prototype or a design. It might be a good moment...

**Comment by WouterSioen** [comment]
We didn't change anything about the structure of fork. If Bram made a prototype, this is probably still respected by the current layout.

All functionality still works exactly the same. It just looks a little different and contains a lot less code we should maintain.

I do agree with you that it could be a great moment to let somebody with a IA/UX background take a look at this. I'll see if I can get somebody involved.

**Comment by jessedobbelaere** [comment]
I agree that there are some/many visual elements that can be improved. I'd also like to distantiate somehow a bit more from the default bootstrap 'look' because it often looks cheap/prototype-alike due to the popularity etc. Would be nice if a UX/designer could help with a few Sketch designs of the important pages & style and the we can take it up where he left.

Some things that I noticed:

* The helvetica font, maybe use the old Lucida Grande again or some beautiful Google fonts like Source Sans Pro?
* Remove these huge asterix icons, a normal * will do, no? image. Same for icons like this: 
image
* Inputfields that are way too wide: http://d.pr/i/zf6f
* I would make the blue Fork logo in the footer gray to make it more subtle
* The file `http://fork-cms-github.fork-cms.dev/src/Backend/Modules/Pages/Layout/Css/Pages.css` and `http://fork-cms-github.fork-cms.dev/src/Backend/Modules/Pages/Layout/Css/pages.css` are both loaded. 
* Save draft & Save buttons are both blue and seem like "one big button", so "save as draft" should have a non-primary color: http://d.pr/i/a8e5
* Installation finished -> shouldn't these be primary buttons? http://d.pr/i/1bgmT
* The user is mentioned twice: http://d.pr/i/13Fpj 
* Floating the addblock buttons causes them not to center: http://d.pr/i/12evZ
* Modal window is aligned to top instead of center like the old one + make "editor" the default in the dropdown: http://d.pr/i/VB33
* When I open ckeditor and select some text, then click the "anchor/create link" button, no modal is showing
* I would put the Add page button to the right, with a colored green icon because it's one of the most important CTA's: http://d.pr/i/qoYv
* There's something that feels weird about this. Maybe the large header, the small margin. I would make the text "there are no tags yet" some kind of soft-yellowish info-alert: http://d.pr/i/HPHP
* Don't make input fields use the full width if it's not need imo: http://d.pr/i/1lPgh
* The translations page: http://d.pr/i/14Q0o
* Users settings: align the edit button to the right: http://d.pr/i/uOcH
* The general settings page could also use some love: http://d.pr/i/11C9J

I can help fixing things, but ideally a UX/designer could first visually design some backend pages, then I can help writing the code to implement it

**Comment by WouterSioen** [comment]
great feedback, thanks!

**Comment by jeroendesloovere** [comment]
:+1: Awesome

**Comment by vytenizs** [comment]
Anytime we can create Bootstrap custom theme to fit Fork CMS style. Main purpose is to have bootstrap and mobile friendly interface. Bootstrap has anything Fork needs for backend. If Fork CMS will ever need custom interface bootstrap supports themes. This job is only base for later improvements.
PS. I was also working on error messages. But now i have to delete branch :D Cuz u completed it faster. :D

**Comment by vytenizs** [comment]
I think button placement should be changed. I should be cool to have at least save button on top too, so you dont have to scroll down when u want to change only top field of a form. For example settings if u change page title u have to scroll all down to the save button.

**Comment by WouterSioen** [comment]
We'll implement a complete new design for the backend. I'll post a preview
of it on monday when I have the files available :)

Op zaterdag 12 maart 2016 heeft Ishiki <notifications@github.com> het
volgende geschreven:

**Comment by vytenizs** [comment]
Do you have date for 2.10 official release?

**Comment by WouterSioen** [comment]
Not yet. The most important parts to be done are these:

* implement the new layout (done by @Katrienvh)
* merge twig and the new bootstrap backend (I'll do this)

I hope to get this done in the upcoming month

**Comment by vytenizs** [comment]
Do you need any help with this or Fork wants to keep all this work by their side? :)

**Comment by WouterSioen** [comment]
I'm right now trying to merge twig in bootstrap, so I hope to have this done soon. @Katrienvh got company time for the backend layout, so this should go rather fast too.

When it's done, I't would be awesome if everyone could test this whole new version and give feedback/fix issues/...

I think working on these big changes with more people would give more merge conflicts (and the amount right now is already rather epic :wink: )

**Comment by vytenizs** [comment]
Well im using this version all the time, so it will be tested real time :D

**Comment by WouterSioen** [comment]
@vytenizs these are the designs (note that they won't be followed 100%, because they contain some new features)

A big thanks to @simohell for making them :)

pasted image at 2016_03_14 09_22-1
pasted image at 2016_03_14 09_22-2
pasted image at 2016_03_14 09_22

**Comment by vytenizs** [comment]
Looks promising :D

**Comment by jeroendesloovere** [comment]
Indeed looks clean.
Just want to say that I'm no fan of the quick menu links (I know that this will be not integrated at the start).
But these links will get abused very quickly.

**Comment by WouterSioen** [comment]
This is a new feature, so it won't be implemented right now. We're first just converting the current functionality to the new design. New features can be added later if everyone agrees on them ;)

**Comment by simohell** [comment]
@jeroendesloovere That was intended to speed up frequent actions specific and relevant to the project. It's was not meant by default but something you can toggle (as the developer) to show/hide here. We have a small module that clears all the cache, minified css, js, template, etc... for us it would be handy to have "clear cache" quick menu... Just an example.

**Comment by WouterSioen** [comment]
We can look into this/discuss it when the new release is done.

**Pull request merged**
