### PR TITLE
Fix incorrect language variable

### PR DESCRIPTION
**Pull request by jessedobbelaere**
## Type

- Non critical bugfix

## Resolves the following issues

/

## Pull request description

Go to the demo for example, http://demo.fork-cms.com/, and checkout the body class. It's empty, should have "en" or "nl" or a language. 
Checkout a dutch frontend website, http://demo.fork-cms.com/nl/blog, the dates are in english instead of dutch.
... numerous other examples

*Why this is happening?*
Everywhere in twig we use `LANGUAGE` which doesn't exist and renders nothing at all. We should use `BACKEND_LANGUAGE` and `FRONTEND_LANGUAGE` to make this working again, right?

### CODE REVIEW

**Comment by carakas** [comment]
I am more in favour of using LANGUAGE everywhere instead of adding the BACKEND and FRONTEND prefix

**Comment by carakas** [comment]
also replacing LANGUAGE with BACKEND_LANGUAGE or FRONTEND_LANGUAGE is not BC

**Comment by carakas** [comment]
is it now a mix of both ?

**Comment by carakas** [comment]
@jessedobbelaere is it now a mix of both ? because I see you removing the LANGUAGE from the backend, so that would not be BC I think

**Comment by jeroendesloovere** [comment]
@jessedobbelaere I prefer LANGUAGE instead of BACKEND_ or FRONTEND_LANGUAGE

**Comment by jessedobbelaere** [comment]
I prefer LANGUAGE too. I just found that LANGUAGE didn't work and FRONTEND_LANGUAGE did, so quickly fixed that. But i'll re-check and try to make LANGUAGE work everywhere

**Comment by jessedobbelaere** [comment]
I added a new const "LANGUAGE" (left the FRONTEND_LANGUAGE const there for backwards compatibility) . Then changed every FRONTEND_LANGUAGE in the frontend to LANGUAGE.

I dunno though, every global constant is prefixed with FRONTEND. If we change language, would that mean we have to change them all to remove FRONTEND_ for consistency sake?
- FRONTEND_CACHE_PATH
- FRONTEND_CACHE_URL
- FRONTEND_CORE_PATH
- FRONTEND_CORE_URL
- FRONTEND_LANGUAGE
- FRONTEND_MODULES_PATH
- FRONTEND_FILES_PATH
- FRONTEND_FILES_URL
- FRONTEND_PATH

Maybe just using `FRONTEND_LANGUAGE` instead of `LANGUAGE` (not working currently) in the current twig templates is an easier solution. 

In the backend however, we use `LANGUAGE` in twig, but thats a twig variable and no global php constant: https://github.com/forkcms/forkcms/blob/master/src/Backend/Core/Engine/TwigTemplate.php#L119

**Pull request merged**
