### PR TITLE
[WIP] The info.xml of the triton theme still referenced the old templates

### PR DESCRIPTION
**Pull request by carakas**

### CODE REVIEW

**Comment by WouterSioen** [comment]
@carakas did you test a clean install after these changes?

**Comment by carakas** [comment]
@WouterSioen I did, but found some more left over SpoonTemplate templates, I will clean up those as well

**Comment by WouterSioen** [comment]
Ok, I'll wait for merging this one.

**Comment by WouterSioen** [comment]
@carakas the follow up stuff will need to be in a separate PR, I'll merge this one to be included in 4.0.2

**Pull request merged**
