### PR TITLE
Remove ping_services from Blog module

### PR DESCRIPTION
**Pull request by ohvitorino**
## Type

- Non critical bugfix

## Resolves the following issues

`ping_services` form field is still being used in the Blog module Add action.

## Pull request description

This PR simply remove the usage of the `ping_services` field and its surrounding SEO panel.

### CODE REVIEW

**Comment by ohvitorino** [comment]
@carakas there is also a usage of ping_services in `test_db.sql`, probably also not necessary. Other than that I don't find other.

**Comment by ohvitorino** [comment]
`ping_services` is being added to the module_settings in `test_db.sql`. Should I remove this one as well?

**Comment by carakas** [comment]
you can remove that one indeed @ohvitorino

**Comment by ohvitorino** [comment]
@carakas f09d18172 remove the insert statement from `test_db.sql`.

**Pull request merged**
