### PR TITLE
Issue 1027

### PR DESCRIPTION
**Pull request by vytenizs**

### CODE REVIEW

**Comment by vytenizs** [comment]
Should i try to merge?

**Comment by vytenizs** [comment]
Done.

**Comment by WouterSioen** [comment]
:+1:

**Comment by vytenizs** [comment]
How is it going?

**Comment by WouterSioen** [comment]
@forkcms/core-contributors I'd propose to merge this in the 3.10 branch and make sure to fix the tests and improve the backend. Everyone ok with this?

**Comment by tijsverkoyen** [comment]
:+1:

**Comment by WouterSioen** [comment]
rebasing it on master is one hell of a job :)

**Comment by Thijzer** [comment]
:+1:

**Pull request merged**
