### PR TITLE
Pagetree update + yarn [WIP]

### LINKED ISSUE #1999: For the Pages module: `yarn add jstree` and `yarn add jquery.cookie`
## Type

- Enhancement

## Problem description

> We want to use `yarn` for the `jstree` in the Backend Pages (& MediaLibrary module). The files from "Pages module" could be replaced by `yarn add jstree` and `yarn add jquery.cookie`. But I was yet unable (lack of time) to get things working, since their are breaking changes in these classes...

## Note

> Address the Pull Request to the "fork-cms-5.0.0-dev" branch

### PR DESCRIPTION
**Pull request by jessedobbelaere**
## Type
- Enhancement
- Feature

## Resolves the following issues
Fixes #1999 

## Pull request description
We used [a very very old version of jsTree from 2009](https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Pages/Js/jstree/jquery.tree.js#L11). So this needs to be updated urgently to the latest version + added to Yarn. 

* I tried to follow the original look & feel of the Fork CMS page tree. Because we cannot use the jQuery pageroller theme anymore, I chose to use a [jstree bootstrap theme](https://github.com/orangehill/jstree-bootstrap-theme) and tweak it in our own sass code until it looks again like the old Fork CMS pagetree (with a few optimizations). 
* Icons are from fontawesome now, instead of our old [fork_icons.png](https://github.com/forkcms/forkcms/search?utf8=%E2%9C%93&q=fork_icons.png&type=) sprite. 
* Was playing with the [jsTree search plugin](https://www.jstree.com/plugins/) that ships by default in jsTree and tried integrating it. End result looks cool, might be handy to include because it makes bigger websites more maintainable if you can find your page to edit fast. 
* Not really related to this ticket, but we have a typeahead.bundle.min.js in our /js folder, but nowhere to be seen in package.json or gulpfile. Added it back because somebody might regenerate the js folder and delete the typeahead file by accident which makes search frontend unusable.

### Video
http://d.pr/v/nrbp2

Still need to handle the drag and drop callbacks and test thorough and do bugfixes...

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
@jessedobbelaere does your PR also contains pagetree-code for the MediaLibrary module?

**Comment by carakas** [comment]
@jessedobbelaere any update on this?

**Comment by carakas** [comment]
@jessedobbelaere any update on this?

**Comment by jeroendesloovere** [comment]
Hi @jessedobbelaere, what's you status?

**Comment by jeroendesloovere** [comment]
@forkcms/core-contributors any frontend dev willing to finish this integration?
Would be awesome, since then we rely on external js and not core js.

**Comment by carakas** [comment]
@jessedobbelaere any update on this?

**Comment by jessedobbelaere** [comment]
I looked at it this weekend but most of the time was used to fix merge conflicts (actually just re-applied my changed on the latest develop). Will try to finish it

**Comment by carakas** [comment]
awesome

**Comment by jeroendesloovere** [comment]
Anybody willing to pick this issue up and fix it?
@Katrienvh, @mathiashelin ?

**Comment by carakas** [comment]
We'll probably wait for this till the backend is switched to BS4

**Comment by carakas** [comment]
This will be done in #2403

**Pull request closed without merging**
