### PR TITLE
Created `App\Domain\ModuleExtra` namespace

### PR DESCRIPTION
**Pull request by jeroendesloovere**
## Type

- Enhancement

## Resolves the following issues

* Classes for ModuleExtraType are al scattered around in Fork.

## Pull request description

* Created the namespace `App\Domain\ModuleExtra` which now holds the classes `Type.php` and `Exception\InvalidType.php`
* This allows that in another PR we can create the `ModuleExtra` entity, repository, ...

### CODE REVIEW

**Comment by StijnVrolijk** [comment]
Why? `ModuleExtraType` is a Value Object thus shouldn't be in in any Domain folder of it's own, nor will there ever be a repository or anything else related to `ModuleExtraType`.

If feel like this is just moving stuff (and creating additional namespaces) in order to move stuff. It serves no purpose

**Comment by jeroendesloovere** [comment]
Hi @StijnVrolijk, like I mentioned in my pull description.
The actual purpose is to place everything in place, so we can then add the long wanted `ModuleExtra` Entity + Repository. Which makes `Type` (= module extra type; block, homepage, widget) exactly in the right position that we want it to be, `App\Domain\ModuleExtra`.

**Comment by jeroendesloovere** [comment]
So `ModuleExtraType` isn't in it's own folder, but in the one for `ModuleExtra`.

**Comment by jeroendesloovere** [comment]
What I provided:
`App\Domain\ModuleExtra\Type`
`App\Domain\ModuleExtra\Exception\InvalidType`

What can later be created in another PR:
`App\Domain\ModuleExtra\ModuleExtra`
`App\Domain\ModuleExtra\ModuleExtraRepository`
...

**Comment by StijnVrolijk** [comment]
You shouldn't move things in advance, you should move them when it makes sense to move them. Now you're creating new namespaces and adding confusion for something that's going to happen soon™.

Also; what are you talking about when you say "the long wanted `ModuleExtra` entity"? Let's focus on getting entities in our modules first. Something about learning to crawl before you start running.

Lastly; who decided everything should be plonked in an `App/Domain` namespace?

**Comment by jeroendesloovere** [comment]
I'm working towards https://gist.github.com/jeroendesloovere/87295062f4281d79cdc90fd882582a71

**Pull request merged**
