### PR TITLE
A button should be a button, not an anchor

### PR DESCRIPTION
**Pull request by StijnVrolijk**
## Type
- Critical bugfix

## Pull request description
A button should be a button, not an anchor
Buttons don't have urls, silly you!

### CODE REVIEW

**Comment by carakas** [comment]
@jeroendesloovere why? is there a reason for it?

**Comment by jeroendesloovere** [comment]
@carakas I have no idea...
I just know that there are "zero search results" for `macro.buttonIcon(null,`.
So to keep everything uniform I suggest we also use `macro.buttonIcon('',` or change everything...

**Comment by jeroendesloovere** [comment]
```
  {# When url is an empty string, use a button, otherwise use a hyperlink/anchor #}
  {% if url %}
```

**Comment by StijnVrolijk** [comment]
Well, the code doesn't do what the comment says it does so something needs to change

**Comment by jeroendesloovere** [comment]
@StijnVrolijk Can you update the comment and change `null` to `''`. Thanks.

**Comment by carakas** [comment]
I actually think that null makes more sense

**Comment by StijnVrolijk** [comment]
@jeroendesloovere updating the comment still allows null :)

**Pull request merged**
