### PR TITLE
Delete useless meta records

### PR DESCRIPTION
**Pull request by bartdc**
This code will delete the meta records when revisions are deleted.

### CODE REVIEW

**Comment by WouterSioen** [comment]
This looks better! :+1:  I'll merge this when the CI has ended.
Thanks!

**Comment by bartdc** [comment]
Great, up to the next pull request (blog autosave, copy a page, link language pages together).

**Comment by WouterSioen** [comment]
Hmm, these sound like big changes. I think it could be better to PR these to the 3.10 branch, since it will already be hard to merge all these big changes together.

**Comment by bartdc** [comment]
Good idea, some of them include DB changes.

**Pull request merged**
