### PR TITLE
Make it possible to send a confirmation mail from the form builder

### PR DESCRIPTION
**Pull request by carakas**
- [x] add missing locals
- [x] prevent the data from being saved when on email only modus
- [x] show message on submission page that the messages aren't being saved into the database

### CODE REVIEW

**Comment by carakas** [comment]
TODO: add implementation for #1547

**Comment by carakas** [comment]
TODO: choose the subject and text that will be in the email to the customer

**Comment by carakas** [comment]
fixes 1053

**Comment by carakas** [comment]
fixes #1053

**Comment by jeroendesloovere** [comment]
When will this be merged?

**Comment by WouterSioen** [comment]
in a major version, since it contains BC breaks.

**Pull request merged**
