### PR TITLE
Profiles installer: locale for labels added

### LINKED ISSUE #1450: Profiles: when installing I want the added pages to be in my language
## Problem

I'm Dutch speaking and when I install the "profiles module" in a (multi)-language website,
lots of new pages get added. But all in English.
So I have to change them all to dutch, french, german manually...

## What I want
That the page-names are in the proper language.

schermafbeelding 2016-04-07 om 16 27 26

### PR DESCRIPTION
**Pull request by jeroendesloovere**
Fixes #1450

### CODE REVIEW

**Comment by carakas** [comment]
did you also test this?

**Comment by carakas** [comment]
both installing from the backend and installing in the installer

**Comment by jeroendesloovere** [comment]
1. Installing from Backend: successfull
2. Installing from installer: not (looking into this)

schermafbeelding 2016-08-25 om 13 41 12

**Comment by carakas** [comment]
you should check if the constant is defined and else provide a fallback

**Comment by jeroendesloovere** [comment]
Can't get things to work... 👎 
schermafbeelding 2016-08-25 om 13 53 27

**Comment by jeroendesloovere** [comment]
Can't get locales to work 👎 
schermafbeelding 2016-08-25 om 14 08 25

**Comment by jeroendesloovere** [comment]
@carakas Works for both the installer and the backend module installer

**Comment by carakas** [comment]
nice :) thanks

**Comment by carakas** [comment]
profile settings locale was missing but I added that in 5ede823 so have a merge ;)

**Pull request merged**
