### PR TITLE
Issue 1443

### PR DESCRIPTION
**Pull request by vytenizs**
As we no longer need full paths for our templates we need to remove them. That is why that hack with '/' was added.

### CODE REVIEW

**Comment by WouterSioen** [comment]
@vytenizs I won't merge this branch because the 3.10 branch is not fully complete here. I'll cherry-pick your commit when https://github.com/katrienvh/forkcms/tree/bootstrap-backend-redesign is merged in 3.10 though.

**Comment by vytenizs** [comment]
Well ok, take a look at my Twig PR. This one does not matter :D

**Comment by WouterSioen** [comment]
This is the relevant commit? https://github.com/vytenizs/forkcms/commit/3532a545afaf09419f77d25f7dffcc59fa243130

**Comment by vytenizs** [comment]
Its for #1445 issue

**Comment by WouterSioen** [comment]
ok, thanks. I'll test it

**Comment by WouterSioen** [comment]
@vytenizs it didn't fully work in all cases. The subpages widget didn't work for examle. I've fixed it in this commit https://github.com/forkcms/forkcms/pull/1447/commits/0e2f379774863b38d662f9f0f24a7eb70acef61f

Which is integrated in this PR: https://github.com/forkcms/forkcms/pull/1447

**Pull request closed without merging**
