### PR TITLE
Add the ability to change the page parameter in the pagination query

### PR DESCRIPTION
**Pull request by jacob-v-dam**

### CODE REVIEW

**Comment by WouterSioen** [comment]
Shouldn't the place where the current page gets fetched be changed too?

**Comment by jacob-v-dam** [comment]
I wouldn't break compatibility, I left the blog module as it is. The module uses 'page' as the parameter query. I made it optional to change the query, by default it will be 'page'.

**Comment by WouterSioen** [comment]
ok 👍

**Comment by tijsverkoyen** [comment]
👍

**Pull request merged**
