### PR TITLE
Upgrade the minimum supported version to 5.5

### LINKED ISSUE #1257: Follow PHP supported versions as minimum support.
see: https://secure.php.net/supported-versions.php

### PR DESCRIPTION
**Pull request by WouterSioen**
Fixes #1257

### CODE REVIEW

**Comment by jonasdekeukelaere** [comment]
You forgot the composer file.

**Comment by WouterSioen** [comment]
good point, I'll add it!

**Comment by WouterSioen** [comment]
@jonasdekeukelaere see 081d38b

**Comment by jonasdekeukelaere** [comment]
:+1:

**Pull request merged**
