### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by WouterSioen**
This pull request applies code style fixes from an analysis carried out by StyleCI.

For more information, click [here](https://styleci.io/analyses/zY9mjz).

### CODE REVIEW

**Comment by WouterSioen** [comment]
StyleCI will analyse new pull requests and will be able to provide automatic patches for this. Would you guys add this integration? @tijsverkoyen @ikoene @Diewy

**Comment by ikoene** [comment]
Sounds great, as long as these automatic patchers are considered safe.

Open source free again I guess? :)

**Comment by WouterSioen** [comment]
Jup, it's free. And the fixer can't merge pull requests. It can only make a branch (on my remote) and make a pull request with it.

This is even optional, you can also just let it check your repositories and pull requests on errors.

**Comment by tijsverkoyen** [comment]
:+1:

**Pull request merged**
