### PR TITLE
Replace SPOON_CHARSET by $container->getParameter('kernel.charset')

### LINKED ISSUE #1138: Replace SPOON_CHARSET by $container->getParameter('kernel.charset')

### PR DESCRIPTION
**Pull request by jeroendesloovere**
Fixes #1138

### CODE REVIEW

**Comment by WouterSioen** [comment]
somebody's on a roll! :+1:

**Comment by jeroendesloovere** [comment]
@WouterSioen If everybody continues to contribute its share of the pie. The symfony conversion will be over soon and w'll be able to create amazing sh*t!

**Comment by WouterSioen** [comment]
You went to fast here. The tests are failing. This could give you a hint: https://travis-ci.org/forkcms/forkcms/jobs/54884901

**Comment by jeroendesloovere** [comment]
Strange, I don't get any error in the backend. I even can use that truncate function without problems...
Could it be that Travis is wrong?

**Comment by jeroendesloovere** [comment]
Is it possible that it fails because 'kernel.charset' is not set in any parameters files (f.e.: parameters.yml.travis)

**Comment by WouterSioen** [comment]
Because it's a unit test, there is no backend model containing a container yet. I would do this: create a mock object "container" that returns 'UTF-8' when getParameter('kernel.charset') is called. Then do a "BackendModel::setContainer()" with this mock object.

If you need more info to create this, I'd be happy to help.

**Comment by WouterSioen** [comment]
You could do something like this:

```php
$containerMock = $this
    ->getMockBuilder('Symfony\Component\DependencyInjection\ContainerInterface')
    ->disableOriginalConstructor()
    ->getMock()
;

$containerMock->expects($this->once())
    ->method('getParameter')
    ->width('kernel.charset')
    ->will($this->returnValue('UTF-8'))
;

BackendModel::setContainer($containerMock);
```

Something like this should work.

**Comment by WouterSioen** [comment]
Hmmm, the $this->once() should be replaced $this->exactly(<number of calls>) or $this->any()

**Comment by WouterSioen** [comment]
Note that you should also be able to remove the `defined('SPOON_CHARSET') || define('SPOON_CHARSET', 'UTF-8');` line

**Comment by WouterSioen** [comment]
And in the frontend the same for frontend.

**Comment by WouterSioen** [comment]
:+1:

**Comment by WouterSioen** [comment]
I'll squash and merge this

**Comment by WouterSioen** [comment]
merged

**Pull request closed without merging**
