### PR TITLE
Feature user templates

### PR DESCRIPTION
**Pull request by carakas**
## Type

- Feature

## TODO

- [x] move example editor templates to the correct place after the bootstrap frontend has been merged
- [x] create documentation PR

## Pull request description

This pr adds a way to let user fill in data but let you keep the control of how they are displayed on the site.

Inside the theme you can define as many of these templates as you want

screenshot of how it looks in the backend
screen shot 2017-01-25 at 11 44 15

The fields are taken dynamically from the template using data attributes

currently supported:

- link
- link-without-content
- text
- textarea
- image
- image-background
- editor

### CODE REVIEW

**Comment by freshface** [comment]
Nice one.

**Comment by freshface** [comment]
URL, e-mail, numeric and required validation would also be nice.
Also a field to add multiple images? For slideshows or lightboxes?

**Comment by carakas** [comment]
@freshface you can always create a PR for that to my branch :)

**Comment by jeroendesloovere** [comment]
Yep, a media library/galleries module integration would be nice.
When I find some time, I will look at this.

**Comment by carakas** [comment]
wait for #1930 to move the templates, apart from that it is finished

**Comment by jeroendesloovere** [comment]
Can you use "yarn" for "Simple Ajax Uploader v2.5.5"?

**Comment by carakas** [comment]
used yarn in a3eb1e8a8

**Pull request merged**
