### PR TITLE
Use proper relative links to docs pages

### PR DESCRIPTION
**Pull request by jessedobbelaere**
## Type

- Non critical bugfix

## Resolves the following issues

/

## Pull request description

Fixes the broken links that are in the documentation currently: https://github.com/forkcms/forkcms/tree/master/docs

* Need to use proper relative links (lose the `docs/` prefix)
* Need to url encode the spaces etc.

Test it out: https://github.com/jessedobbelaere/forkcms/tree/fix-documentation-links/docs

### CODE REVIEW

**Comment by carakas** [comment]
do the links then also still work when you open them in your IDE?

**Comment by jessedobbelaere** [comment]
Yep IDE's are smart enough :)

screen capture on 2017-12-30 at 18-37-51

**Comment by carakas** [comment]
@jessedobbelaere can you look at the conflicts?

**Comment by jessedobbelaere** [comment]
@carakas done :) !

**Pull request merged**
