### PR TITLE
Inverted Backend import/export icons

### LINKED ISSUE #1213: Import and export icons direction inverted
Hi Guys,

Looking at the export and import icons direciton in "Backend->Settings->Translations" I have a strange feeling. They don't look right, normally the import should have the arrow down because we are pulling data, and an arrow up for the export because we are pushing data out.

### PR DESCRIPTION
**Pull request by jeroendesloovere**
Fixes #1213

### CODE REVIEW

**Comment by WouterSioen** [comment]
I don't agree here. I think the icons are logical the way they are now. An export has a down arrow in my opinion, since it **down**loads stuff for you, and an import has an up arrow since you'll **up**load stuff.

**Comment by jeroendesloovere** [comment]
@WouterSioen I follow what @GhaziTriki said.
Because in the history I've also found the icons confusing...

This is how it was: 
schermafbeelding 2015-05-27 om 16 26 19

This is how it will be:
import-export-after

Examples in real life: Apple
They also use an arrow that points up for their "exporting" features.
schermafbeelding 2015-05-27 om 16 29 25

**Comment by jeroendesloovere** [comment]
I've been an Mac user for a decade now and for me the "up" arrow is similar to "export/share/...". But I still remember that IE and Firefox for Windows use a "down" arrow for downloads...

**Comment by WouterSioen** [comment]
http://www.fork-cms.com/ also uses a down arrow for download :)

**Comment by jeroendesloovere** [comment]
@WouterSioen Yes, and I also found it obvious on that particular location that the arrow is pointing down...

**Comment by jeroendesloovere** [comment]
I find that there's a distinction between "export" and "download". For download I would use "down" arrow en for export an up arrow... Strange shizzle...

**Comment by WouterSioen** [comment]
In my opinion, an export is a download of some data in a certain format.

**Comment by jeroendesloovere** [comment]
Endless discussion I guess.
Maybe we can add a "checkbox" in the core, so users can choose their preferred solution. :-P LOL

**Comment by WouterSioen** [comment]
Please, let's not go there :p

**Comment by GhaziTriki** [comment]
I think I will regret for starting this conversation :laughing:, normally in ergonomics if you choose a label then you choose an icon to go well with it. Actually download and export labels are different even if they have the same meaning, the export have the meaning of pulling out something, but downloading have the meaning of pulling in something.

**Comment by WouterSioen** [comment]
I'll check how the export icons look in the bootstrap implementation.

**Comment by WouterSioen** [comment]
Looks like it will be fixed when the bootstrap implementation is merged:

**Comment by jeroendesloovere** [comment]
Thank god its closed :-P :+1:

**Pull request closed without merging**
