### PR TITLE
Use help-block instead of text-info

### LINKED ISSUE #1600: Installation contains invisible text
schermafbeelding 2016-07-01 om 20 01 27
schermafbeelding 2016-07-01 om 20 01 31

### PR DESCRIPTION
**Pull request by bjorvack**
closes #1600

### CODE REVIEW

**Comment by carakas** [comment]
I would rather fix the css than remove to remove the class name

**Comment by StijnVrolijk** [comment]
@carakas this might affect things elsewhere. I'm also for changing the CSS but be sure to check for usage, @bjorvack

**Comment by carakas** [comment]
@bjorvack even better might be to use the bootstrap class that exists for this `help-block`

**Comment by WouterSioen** [comment]
+1 for help block instead of the custom class

**Pull request merged**
