### PR TITLE
Improvement: New MailMotor integrated in 3.10

### PR DESCRIPTION
**Pull request by jeroendesloovere**
### Improvements

* MailMotor: removed old one and added the new MailMotor.

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
PR for https://github.com/forkcms/forkcms/issues/1164

**Comment by WouterSioen** [comment]
style ci fails

**Comment by jeroendesloovere** [comment]
That's because branch 3.10 fails.

**Comment by WouterSioen** [comment]
@jeroendesloovere Can you do a new PR using twig? (sorry, giving you lot's of work)

**Comment by jeroendesloovere** [comment]
I'll open up a new PR with Twig when I found the time.

**Pull request closed without merging**
