### PR TITLE
Location module doctrine integration

### PR DESCRIPTION
**Pull request by MathiasDewelde**
Doctrine integration in frontend and backend.

Only works using #1029 (needs a solution to pass the doctrine entity to JS data).

### CODE REVIEW

**Comment by WouterSioen** [comment]
@MathiasDewelde if you change the jsData to work without this Serializer PR, I'll merge this.

**Comment by MathiasDewelde** [comment]
PR #1060 is required to get this PR working.

**Comment by WouterSioen** [comment]
can't you just do `$this->addJSData('settings', $this->settings->toJSData());` instead off changing the addJSData method?

**Comment by MathiasDewelde** [comment]
Ok time to wake up :D

**Pull request merged**
