### PR TITLE
Show session timeout warning 15min after page load

### PR DESCRIPTION
**Pull request by Katrienvh**
## Type
- Enhancement

## Resolves the following issues
Losing changes because your session expired without any warning.

## Pull request description
Now there will appear a warning 15 minutes after page load, with the message to recommend the user to (temporary) save the changes that are made.

### CODE REVIEW

**Comment by carakas** [comment]
@Katrienvh is session timeout on all servers the same? Wouldn't it be better to look at the server config and then subtract like 5 minutes or so?

**Comment by StijnVrolijk** [comment]
What if the "save" action uses an ajax call? Wouldn't the message have to be shown again after x minutes?

**Comment by Katrienvh** [comment]
> What if the "save" action uses an ajax call? Wouldn't the message have to be shown again after x minutes?

**Comment by Katrienvh** [comment]
> What if the "save" action uses an ajax call? Wouldn't the message have to be shown again after x minutes?
@StijnVrolijk fixed in 9e03fd6

**Pull request merged**
