### PR TITLE
Twig into 3.10

### PR DESCRIPTION
**Pull request by Thijzer**
as requested

### CODE REVIEW

**Comment by Thijzer** [comment]
Is everything in order @WouterSioen?

**Comment by WouterSioen** [comment]
Yes, I'm just waiting to merge this, for a moment when I have time to fix the tests directly after merging ;)

**Comment by Thijzer** [comment]
Ok great!

**Comment by WouterSioen** [comment]
I've merged this from a different branch after fixing the tests. Thanks a lot for this!

**Pull request closed without merging**
