### PR TITLE
Fix broken URLs

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by crydotsnake** [comment]
Hello @jessedobbelaere!, @carakas Say to me that the urls wont work anymore in the md files if the docs site has moved on. Do you have maybe an idea what to do?.

**Comment by jessedobbelaere** [comment]
> Hello @jessedobbelaere!, @carakas Said to me that the urls wont work anymore in the md files if the docs site has moved on. Do you have maybe an idea what to do?.

Hi! I think you should use relative url's here. The docs website runs a `documentation` module I created, and strips the `.md` extension from the url so you can see a working link here:

https://docs.fork-cms.com/documentation/detail/installation/installation-wizard#user-content-step-7-finishing (link on: **start configuring**)

```markdown
If the installation is finished you can [start configuring](../02.%20getting%20started/01.%20introduction.md) your website and tools.
```
from https://github.com/forkcms/forkcms/blob/master/docs/01.%20installation/02.%20installation_wizard.md

that way, the link still works on the markdown preview of github, but also on the website :)

**Comment by jessedobbelaere** [comment]
Not sure if I understand the issue, as the link on the [docs page](https://docs.fork-cms.com/documentation/detail/media-library/introduction) and the [markdown version](https://github.com/forkcms/forkcms/blob/master/docs/07.%20media%20library/01.%20introduction.md) seem to work here 👀

**Comment by crydotsnake** [comment]
Hm... did i something wrong?.

**Comment by crydotsnake** [comment]
Hm yes. i get some broken links.. But how i can fix those?.

**Comment by crydotsnake** [comment]
I get also some broken image links

**Comment by crydotsnake** [comment]
This is also confusing:

`[documentation](https://github.com/forkcms/forkcms/tree/master/docs)` in `06.contribute/01. introduction.md` redirects me to the old documentation

**Comment by jessedobbelaere** [comment]
Should definitely not contain the full url (github.com/forkcms/forkcms, but rather using relative urls :-)

**Comment by crydotsnake** [comment]
You mean, this is normal?.

I dont know where to start fixing the urls 😕

**Comment by jessedobbelaere** [comment]
I would just use a tool like I described above or maybe a website like https://www.deadlinkchecker.com/, check the docs source code and try to fix them :D But as I mentioned the links you mentioned are working on my end so thats strange:

> Not sure if I understand the issue, as the link on the [docs page](https://docs.fork-cms.com/documentation/detail/media-library/introduction) and the [markdown version](https://github.com/forkcms/forkcms/blob/master/docs/07.%20media%20library/01.%20introduction.md) seem to work here 👀

The things that need fixing are the 404 errors on images and links that they tool complains about :-)

**Pull request closed without merging**
