### PR TITLE
Fix google analytics

### PR DESCRIPTION
**Pull request by jonasdekeukelaere**
## Type
- Critical bugfix

## Pull request description
The Connector::getAnalyticsData should return an array, but the call make in this method, returns
a Google_Service_Analytics_GaData object.

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
Hi there,
This is related to https://github.com/forkcms/forkcms/pull/2288.
Return data is not an array, but is indeed Google_Service_Analytics_GaData.
I've already fixed this in a PR, but I need to update the test cases...

**Comment by jeroendesloovere** [comment]
Or I can close my PR and we only accept array like you are doing.
@carakas you decide...

**Comment by jonasdekeukelaere** [comment]
Fixed in 7355a7250

**Comment by carakas** [comment]
@jeroendesloovere can you check this one again?

**Comment by carakas** [comment]
@jonasdekeukelaere do you get errors when you run `yarn test`

**Comment by jeroendesloovere** [comment]
Can anybody confirm that the stats are working?
I just deployed a fork cms v5.0.6 and the charts are not working...

schermafbeelding 2017-12-07 om 11 08 14

schermafbeelding 2017-12-07 om 11 08 20

**Pull request merged**
