### PR TITLE
Use templating services

### PR DESCRIPTION
**Pull request by vytenizs**
Just updates from master and 3.10. Added some fixes that throws exceptions. Starting to test it on new project.

### CODE REVIEW

**Comment by vytenizs** [comment]
I will constantly make follow ups here.

**Comment by vytenizs** [comment]
At the moment this version is unusable. Pages cannot be created. Forms are missing lots of fields. I dunno why Backend uses Frontend Twig extensions. One HUGE issue is that u cannot include fields from other files cuz loss of form variable, Twig just throws exception that u are trying to render field outside form.

**Comment by WouterSioen** [comment]
@vytenizs a lot of this stuff is already fixed in https://github.com/katrienvh/forkcms/tree/bootstrap-backend-redesign

This is where the new design is being implemented (and a lot of the issues are being fixed, to be able to implement the design)

**Comment by vytenizs** [comment]
So which one branch should i test? :D

**Comment by WouterSioen** [comment]
This bootstrap-backend-redesign branch will be merged in 3.10 as soon as the design is finished. I hope everyone will be able to test this on the 3.10 branch asap :)

**Comment by WouterSioen** [comment]
I'm also setting up an online demo for it. I'll push it on the fork cms slack when the design is implemented.

**Comment by WouterSioen** [comment]
see https://github.com/forkcms/forkcms/pull/1447

**Pull request closed without merging**
