### PR TITLE
adds a function to checkboxes to get enum values easier

### PR DESCRIPTION
**Pull request by carakas**

### CODE REVIEW

**Comment by WouterSioen** [comment]
It would be nice if you would change this in the existing modules too.

**Comment by carakas** [comment]
I'll see if I feel like being nice tonight

**Comment by WouterSioen** [comment]
Two points to be changed:

* rename method: "getActualValue" or something more logical.
* implement this in the existing modules or be nice.

**Comment by carakas** [comment]
The 2 points have been changed

**Pull request merged**
